 name: CI

 on:
   push:
     branches: [ main, master ]
   pull_request:
     branches: [ main, master ]

 jobs:
   lint-and-build:
     runs-on: ubuntu-latest
     strategy:
       matrix:
         python-version: ["3.10", "3.11", "3.12"]
     steps:
       - uses: actions/checkout@v4
       - uses: actions/setup-python@v5
         with:
           python-version: ${{ matrix.python-version }}
       - name: Upgrade pip
         run: python -m pip install --upgrade pip
       - name: Install dev tools
         run: pip install ruff black
       - name: Install package
         run: pip install -e ".[dev]"
       - name: Ruff lint
         run: ruff check .
       - name: Black check
         run: black --check .
       - name: CLI smoke tests
         run: |
           python -c "import envtrace; print(envtrace.__version__)"
           envtrace version